<?php

/**
 * @file
 * Functions to support theming in the Drupal Training theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function drupal_training_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function drupal_training_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function drupal_training_preprocess_node(&$variables) {

}
